[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Jonas Obrist <jonas.obrist@hennge.com>"]
edition = "2018"

[dependencies]
itertools = "0.8.2"
rayon = "1.2.1"
threadpool = "1.7.1"
regex = "1.3.1"
pathfinding = "2.0.3"
